### PR TITLE
Changing srpm mapping method

### PR DESCRIPTION
**Pull request by mkulik-rh**
Previous method worked pretty good and fast but it was to trivial. One macro in Name line in spec file would break it. We could simply parse spec file but that is expensive and unnecessary. We only want to know name of the package, nothing else.

My new method is fast and should be 99.9% reliable or even more. It also require no additional dependency only python 3.8.

py38 is required because Walrus Operator are extremely handy to use while reading binary files.

### CODE REVIEW

**Comment by mkulik-rh** [comment]
Rebased, because null termination byte is unnecessary.

**Comment by mcurlej** [comment]
Looks good. Can you also the write a unittest to test the change?

**Comment by mkulik-rh** [comment]
Added `test_srpm_mapping_with_invalid_files` to cover rpm mapping method.

Based on queue branch should be merged after it.

**Comment by mcurlej** [comment]
I will merge this but py38 dependency can bite in the ass later, but we can resolve that later. Thanks.

**Pull request merged**
